services:
  activemq:
    image: apache/activemq-artemis:2.30.0
    ports:
      - "8161:8161"
      - "61616:61616"
    volumes:
      - /docker/activemq/config/broker.xml:/var/lib/artemis/etc/broker.xml
  redis:
    image: redis
    ports:
      - 6379:6379
